GET http://localhost:8080/jobs/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyMSIsInVzZXJfaWQiOjEsImlzX2FkbWluIjpmYWxzZSwiZXhwIjoxNzMwNjQyMDEzfQ.YLwG6Dn-hi5dDMv6m-svFQT8Oc9JY9U828F1uit5Ll8